---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
library(janitor)
library(infer)
library(skimr)
```

```{r}
ames <- read_csv("data/ames.csv")

ames
```

```{r}
ames <- clean_names(ames)
```

```{r}
glimpse(ames)
```

```{r}
view(ames)
```


```{r}
ames %>% 
  ggplot(aes(x = lot_area)) +
  geom_histogram(col = "white", bins = 90)
```


This isn't a great distribution. It has one large peak and very little distribution. 

```{r}
single_sample <- ames %>% 
  rep_sample_n(size = 100, reps = 1) %>% 
  ungroup() %>% 
  select(lot_area)

single_sample
```

```{r}
boot_strap_sample <- single_sample %>% 
  rep_sample_n(size = 100, replace = TRUE, reps = 1000) %>% 
  group_by(replicate) %>% 
  summarise(mean_lot_area = mean(lot_area))
```

```{r}
boot_strap_sample %>% 
  ggplot(aes(x = mean_lot_area)) +
  geom_histogram(col= "white", bins = 60)
```

```{r}
boot_strap_sample %>% 
  summarise(sterr = sd(mean_lot_area))
```

```{r}
boot_strap_sample %>% 
  summarise(
    mean = mean(mean_lot_area),
    lower = quantile(mean_lot_area, probs = 0.025),
    higher = quantile(mean_lot_area, probs = 0.975)
  )
```

```{r}
boot_strap_sample <- single_sample %>% 
  specify(response = lot_area) %>% 
  generate(reps = 1000, type = "bootstrap") %>% 
  calculate(stat = "mean")

boot_strap_sample
```

```{r}
boot_strap_sample_ci <- boot_strap_sample %>% 
  get_ci(level = 0.95, type = "percentile")

boot_strap_sample_ci
```

```{r}
boot_strap_sample %>% 
  visualise() +
  shade_confidence_interval(endpoints = boot_strap_sample_ci)
```

```{r}
boot_strap_sample %>% 
  summarise(mean(stat))
```

```{r}
boot_strap_sample_ci_99 <- boot_strap_sample %>% 
  get_ci(level = 0.99, type = "percentile")

boot_strap_sample_ci_99
```

```{r}
boot_strap_sample %>% 
  visualise() +
  shade_confidence_interval(endpoints = boot_strap_sample_ci_99)
```













