---
title: "R Notebook"
output: html_notebook
---

```{r}
library(tidyverse)
```

```{r}
health_board <- read_csv("data/opendata_inc9418_hb.csv")
```

```{r}
class(health_board)
```

```{r}
dim(health_board)
```

```{r}
names(health_board)
```

```{r}
view(health_board)
```

```{r}
health_board %>%
  filter(HB == "S08000016") %>% 
  filter(CancerSite == "All cancer types") %>% 
  ggplot(aes(x = Year, y = IncidencesAllAges) )+
  geom_line()
```

```{r}
health_board %>% 
  filter(HB == "S08000016", CancerSite == "All cancer types") %>% 
  group_by(CancerSite) %>% 
  ggplot(aes(x = Year, fill = CancerSite)) +
  geom_bar()
```

```{r}
unique(health_board$CancerSite)
```

```{r}
health_board %>% 
  filter(HB == "S08000016") %>% 
  group_by(CancerSite) %>% 
  summarise()
```

```{r}
region <- read_csv("data/opendata_inc9418_region.csv")
```

```{r}
region
```

```{r}
view(region)
```

```{r}
scotland <- read_csv("data/opendata_inc9418_scotland.csv")
```

```{r}
view(scotland)
```

```{r}
health_board
```


```{r}
health_board %>% 
  filter(HB == "S08000016") %>% 
  filter(CancerSite == "All cancer types") %>% 
  ggplot(aes(x = Year, y = Sex)) +
  geom_point()
```





















